plotLoggedSignal2x2(out.logsout, ...
    {{'6SC_ua','6SC_ub','6SC_uc'}, {'Sin_ua','Sin_ub','Sin_uc'}, ...
     {'6SC_ia','6SC_ib','6SC_ic'}, {'Sin_ia','Sin_ib','Sin_ic'}}, ...
    'YLabel', {'Voltage','','Current',''}, ...
    'XLabel', {[], [], 'Time', 'Time'}, ...
    'Title',  {'Six-Step Commutation','Sinusoidal Commutation','',''}, ...
    'XLim', [1.499 1.5], ...
    'YLim', {[-20 20], [-70 70]}, ...
    'ShowXTickLabels', [false false false false], ...
    'ShowYTickLabels', [false false false false], ...
    'ExportName', 'WaveformsArbitrarySetpoints');

plotLoggedSignal3x1(out.logsout, ...
    {{'6SC_ia','6SC_ib','6SC_ic'}, {'Sin_ia','Sin_ib','Sin_ic'},...
    {'FOC_ia', 'FOC_ib', 'FOC_ic'}}, ...
    'YLabel', {'Voltage','','Current',''}, ...
    'XLabel', {[], [], 'Time', 'Time'}, ...
    'Title',  {'Six-Step Commutation','Sinusoidal Commutation','',''}, ...
    'XLim', [1.49 1.5], ...
    'YLim', {[-20 20], [-70 70]}, ...
    'ShowXTickLabels', [false false false false], ...
    'ShowYTickLabels', [false false false false])