%% OL Arbitrary Setpoints
% plotLoggedSignal2x2(out.logsout, ...
%     {{'6SC_ua','6SC_ub','6SC_uc'}, {'Sin_ua','Sin_ub','Sin_uc'}, ...
%      {'6SC_ia','6SC_ib','6SC_ic'}, {'Sin_ia','Sin_ib','Sin_ic'}}, ...
%     'YLabel', {'Voltage','','Current',''}, ...
%     'XLabel', {[], [], 'Time', 'Time'}, ...
%     'Title',  {'Six-Step Commutation','Sinusoidal Commutation','',''}, ...
%     'XLim', [1.499 1.5], ...
%     'YLim', {[-20 20], [-70 70]}, ...
%     'ShowXTickLabels', [false false false false], ...
%     'ShowYTickLabels', [false false false false], ...
%     'ExportName', 'WaveformsArbitrarySetpoints');

% %% OL1: Currents
% plotLoggedSignal3x1(out.logsout, ...
%     {{'6SC_ia','6SC_ib','6SC_ic'}, {'Sin_ia','Sin_ib','Sin_ic'}, ...
%      {'FOC_ia','FOC_ib','FOC_ic'}}, ...
%     'YLabel', {'Current','Current','Current'}, ...
%     'XLabel', {[], [], 'Time'}, ...
%     'Title',  {'Six-Step Commutation','Sinusoidal Commutation','Field-Oriented Control'}, ...
%     'XLim', [1.45 1.5], ...
%     'ShowXTickLabels', [true true true], ...
%     'ShowYTickLabels', [true true true], ...
%     'ExportName', 'OL1_Currents')

%% OL1: 6SC Current
% plotLoggedSignal1x1(out.logsout, ...
%     {'6SC_ia','6SC_ib','6SC_ic'}, ...
%     'YLabel', 'Current [A]', ...
%     'XLabel', 'Time [s]', ...
%     'Title',  '', ...
%     'XLim', [1.45 1.5], ...
%     'ShowXTickLabels', true, ...
%     'ShowYTickLabels', true, ...
%     'ExportName', 'OL1_6SC_Current')

%% OL1: Torque
% plotLoggedSignal1x1(out.logsout, ...
%     {'6SC_Te','Sin_Te','FOC_Te'}, ...
%     'YLabel', 'Electrical Torque [Nm]', ...
%     'XLabel', 'Time [s]', ...
%     'Title',  '', ...
%     'XLim', [1.45 1.5], ...
%     'ShowXTickLabels', true, ...
%     'ShowYTickLabels', true, ...
%     'ExportName', 'OL1_Torque')

%% OL1: Torque and Speed
% plotLoggedSignal1x2(out.logsout, ...
%     {{'6SC_Te','Sin_Te','FOC_Te'}, {'6SC_wm','Sin_wm','FOC_wm'}}, ...
%     'YLabel', {'Electrical Torque [Nm]','Angular Velocity [rad/s]'}, ...
%     'XLabel', {'Time [s]', 'Time [s]'}, ...
%     'Title',  {'Electrical Torque','Angular Velocity'}, ...
%     'XLim', [1.45 1.5], ...
%     'ShowXTickLabels', [true true], ...
%     'ShowYTickLabels', [true true], ...
%     'ExportName', 'OL1_TorqueVelocity')

%% OL1: Speed
% plotLoggedSignal1x2(out.logsout, ...
%     {{'6SC_wm','Sin_wm','FOC_wm'}, '6SC_wm'}, ...
%     'YLabel', {'Angular Velocity [rad/s]',''}, ...
%     'XLabel', {'Time [s]', 'Time [s]'}, ...
%     'Title',  {'Angular Velocity','Six-Step Velocity'}, ...
%     'XLim', [1.45 1.5], ...
%     'ShowXTickLabels', [true true], ...
%     'ShowYTickLabels', [true true], ...
%     'ExportName', 'OL1_Velocity')

%% OL1: Torque and Power
% plotLoggedSignal1x2(out.logsout, ...
%     {{'6SC_Te','Sin_Te','FOC_Te'}, {'6SC_Pel','Sin_Pel','FOC_Pel'}}, ...
%     'YLabel', {'Electrical Torque [Nm]','Electrical Power [W]'}, ...
%     'XLabel', {'Time [s]', 'Time [s]'}, ...
%     'Title',  {'Electrical Torque','Electrical Power'}, ...
%     'XLim', [1.45 1.5], ...
%     'ShowXTickLabels', [true true], ...
%     'ShowYTickLabels', [true true], ...
%     'ExportName', 'OL1_TorquePower')

%% OL2: Speed
% plotLoggedSignal1x2(out.logsout, ...
%     {{'6SC_wm','Sin_wm','FOC_wm'}, '6SC_wm'}, ...
%     'YLabel', {'Angular Velocity [rad/s]',''}, ...
%     'XLabel', {'Time [s]', 'Time [s]'}, ...
%     'Title',  {'Angular Velocity','Six-Step Velocity'}, ...
%     'XLim', [1.498 1.5], ...
%     'ShowXTickLabels', [true true], ...
%     'ShowYTickLabels', [true true], ...
%     'ExportName', 'OL2_Velocity')

%% OL2: 6SC currents
% plotLoggedSignal1x1(out.logsout, ...
%     {'6SC_ia','6SC_ib','6SC_ic'}, ...
%     'YLabel', 'Current [A]', ...
%     'XLabel', 'Time [s]', ...
%     'Title',  '', ...
%     'XLim', [1.495 1.5], ...
%     'ShowXTickLabels', true, ...
%     'ShowYTickLabels', true, ...
%     'ExportName', 'OL3_6SC_Current')

%% OL1: 6SC Current
% plotLoggedSignal1x1(out.logsout, ...
%     {'FOC_iq'}, ...
%     'YLabel', 'Current [A]', ...
%     'XLabel', 'Time [s]', ...
%     'Title',  '', ...
%     'XLim', [0 0.5], ...
%     'ShowXTickLabels', true, ...
%     'ShowYTickLabels', true, ...
%     'ExportName', 'OL4_FOC_idiq')

%% Speed, idc
% plotLoggedSignal1x2(out.logsout, ...
%     {{'6SC_wm','Sin_wm','FOC_wm', 'wm*'}, {'6SC_idc','Sin_idc','FOC_idc'}}, ...
%     'YLabel', {'Angular Velocity [rad/s]','Current [A]'}, ...
%     'XLabel', {'Time [s]', 'Time [s]'}, ...
%     'Title',  {'Angular Velocity','DC-Current'}, ...
%     'XLim', [0.08 0.2], ...
%     'ShowXTickLabels', [true true], ...
%     'ShowYTickLabels', [true true], ...
%     'ExportName', 'CL2_VelocityCurrent_FOCLimit');

%% CL2: Speed
% plotLoggedSignal1x1(out.logsout, ...
%     {'6SC_wm','Sin_wm','FOC_wm','wm*'}, ...
%     'YLabel', 'Angular Velocity [rad/s]', ...
%     'XLabel', 'Time [s]', ...
%     'Title',  '', ...
%     'XLim', [0.08 0.2], ...
%     'ShowXTickLabels', true, ...
%     'ShowYTickLabels', true, ...
%     'ExportName', 'CL2_Speed')

%% CL2: Speed, Power
% plotLoggedSignal1x2(out.logsout, ...
%      {{'6SC_wm','Sin_wm','FOC_wm'}, {'6SC_Pel','Sin_Pel','FOC_Pel'}}, ...
%      'YLabel', {'Angular Velocity [rad/s]','Electromagnetic Power [W]'}, ...
%      'XLabel', {'Time [s]', 'Time [s]'}, ...
%      'Title',  {'Angular Velocity','Electromagnetic Power'}, ...
%      'XLim', [0.975 1], ...
%      'ShowXTickLabels', [true true], ...
%      'ShowYTickLabels', [true true], ...
%      'ExportName', 'CL1_SpeedPower')

%% CL2: DC Current at step
% plotLoggedSignal1x1(out.logsout, ...
%     {'6SC_idc', 'Sin_idc', 'FOC_idc'}, ...
%     'YLabel', 'Current [A]', ...
%     'XLabel', 'Time [s]', ...
%     'Title',  '', ...
%     'XLim', [0.1 0.1005], ...
%     'ShowXTickLabels', true, ...
%     'ShowYTickLabels', true, ...
%     'ExportName', '')

%% CL2: Currents
% plotLoggedSignal1x2(out.logsout, ...
%     {{'6SC_idc','Sin_idc','FOC_idc'}, '6SC_wm'}, ...
%     'YLabel', {'Angular Velocity [rad/s]',''}, ...
%     'XLabel', {'Time [s]', 'Time [s]'}, ...
%     'Title',  {'Angular Velocity','Six-Step Velocity'}, ...
%     'XLim', [1.498 1.5], ...
%     'ShowXTickLabels', [true true], ...
%     'ShowYTickLabels', [true true], ...
%     'ExportName', 'OL2_Velocity')