M48
; DRILL file {KiCad 7.0.10} date Tue Jul 28 14:56:26 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-28T14:56:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.450
%
G90
G05
T1
X82.759Y-84.374
X95.459Y-84.374
X135.856Y-72.654
X148.556Y-72.654
M30
